repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        exclude: ^sites/
      - id: end-of-file-fixer
        exclude: ^signature/css/signature.css.map|^sites/
      - id: check-yaml
      - id: check-added-large-files
        exclude: ^signature/assets/current_banner.png

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.1
    hooks:
      - id: ruff
      - id: ruff-format
